In [2]:
import torch
print(torch.__version__)

2.10.0+cu128


In [3]:
if torch.cuda.is_available():
  print('GPU is availabel')
  print(f'Using GPU:{torch.cuda.get_device_name(0)}')
else:
  print('GPU not available Using CPU')

GPU is availabel
Using GPU:Tesla T4


# Tensor Operation on GPU

In [4]:
torch.cuda.is_available()

True

In [5]:
device = torch.device('cuda')

In [6]:
device

device(type='cuda')

- Create a new tensor on GPU

In [7]:
torch.rand((2,3),device=device)

tensor([[0.9571, 0.3975, 0.7674],
        [0.3333, 0.3478, 0.2946]], device='cuda:0')

- moving an existing tensor to GPU

In [8]:
a = torch.rand(2,3)
a

tensor([[0.5447, 0.8727, 0.0091],
        [0.2972, 0.4734, 0.6183]])

In [10]:
b=a.to(device)

In [11]:
b

tensor([[0.5447, 0.8727, 0.0091],
        [0.2972, 0.4734, 0.6183]], device='cuda:0')

In [12]:
b+5

tensor([[5.5447, 5.8727, 5.0091],
        [5.2972, 5.4734, 5.6183]], device='cuda:0')

In [15]:
import torch
import time

# Define the size of the matrices
size = 10000 # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1=torch.randn(size,size)
matrix_cpu2=torch.randn(size,size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2) # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f'Time on CPU: {cpu_time:.4f} seconds')

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time = time.time() - start_time


print(f'Time on GPU:{gpu_time:.4f} seconds')

# Compare result
print('\nSpeedup (CPU time / GPU time):',cpu_time / gpu_time)

Time on CPU: 16.1221 seconds
Time on GPU:0.6656 seconds

Speedup (CPU time / GPU time): 24.22086163593199


# Reshaping Tensors

In [16]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

- reshape

In [17]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

- flatten

In [18]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
b = torch.rand(2,3,4)
b

tensor([[[0.3607, 0.5193, 0.7885, 0.2931],
         [0.0558, 0.0227, 0.7561, 0.1564],
         [0.4002, 0.1403, 0.4429, 0.1523]],

        [[0.6333, 0.2024, 0.2739, 0.9992],
         [0.4083, 0.7359, 0.9252, 0.2783],
         [0.8408, 0.0017, 0.0560, 0.1641]]])

- permute

In [20]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [21]:
b.permute(0,2,1).shape

torch.Size([2, 4, 3])

In [22]:
b.permute(0,2,1)

tensor([[[0.3607, 0.0558, 0.4002],
         [0.5193, 0.0227, 0.1403],
         [0.7885, 0.7561, 0.4429],
         [0.2931, 0.1564, 0.1523]],

        [[0.6333, 0.4083, 0.8408],
         [0.2024, 0.7359, 0.0017],
         [0.2739, 0.9252, 0.0560],
         [0.9992, 0.2783, 0.1641]]])

- unsqueeze

In [23]:
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [24]:
c = torch.rand(226,226,3)
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [25]:
c = torch.rand(226,226,3)
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

- squeeze

In [30]:
d = torch.rand(1,20)
d.squeeze(0)

tensor([0.5492, 0.9504, 0.6037, 0.8153, 0.4655, 0.9644, 0.1169, 0.1780, 0.3398,
        0.9715, 0.5172, 0.5238, 0.9865, 0.4645, 0.0049, 0.3443, 0.5517, 0.2581,
        0.6848, 0.9477])

In [31]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

Numpy and PyTorch

In [32]:
import numpy as np

In [33]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [34]:
b = a.numpy()

In [35]:
b

array([1, 2, 3])

In [36]:
type(b)

numpy.ndarray

In [37]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [40]:
t=torch.from_numpy(c)

In [41]:
type(t)

torch.Tensor