In [53]:
import torch
print(torch.__version__)

2.10.0+cu128


In [54]:
if torch.cuda.is_available():
  print('GPU is availabel')
  print(f'Using GPU:{torch.cuda.get_device_name(0)}')
else:
  print('GPU not available Using CPU')

GPU is availabel
Using GPU:Tesla T4


# Create a Tensor

- using empty

In [55]:
torch.empty(2,3)

tensor([[-8.8229e-16,  4.3935e-41,  1.2914e+05],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

- check type

In [56]:
a = torch.empty(2,3)
type(a)

torch.Tensor

- using zeros

In [57]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [58]:
torch.zeros(5,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

- using ones

In [59]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

- using rand

In [60]:
torch.rand(2,3)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])

- use of seed

In [61]:
torch.rand(4,4)

tensor([[0.5557, 0.9770, 0.4440, 0.9478],
        [0.7445, 0.4892, 0.2426, 0.7003],
        [0.5277, 0.2472, 0.7909, 0.4235],
        [0.0169, 0.2209, 0.9535, 0.7064]])

- manual_seed

In [62]:
torch.manual_seed(100)
torch.rand(4,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183, 0.9014]])

In [63]:
torch.manual_seed(100)
torch.rand(4,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183, 0.9014]])

- using tensor

In [64]:
torch.tensor([1,2,3,4])

tensor([1, 2, 3, 4])

In [65]:
torch.tensor([[1,2,3,4],[5,6,7,8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

- other ways

In [66]:
# arange
print('using arange:',torch.arange(2,20,2))

# using linspace
print('using linspace:',torch.linspace(2,20,5))

# using eye
print('using eye:',torch.eye(5))

# using full
print('using full:',torch.full((3,3),5))

using arange: tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])
using linspace: tensor([ 2.0000,  6.5000, 11.0000, 15.5000, 20.0000])
using eye: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full: tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [67]:
x = torch.tensor([[1,2,3,4],[5,6,7,8],[7,8,9,9]])
print(x)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [7, 8, 9, 9]])


In [68]:
x.shape

torch.Size([3, 4])

In [69]:
torch.empty_like(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [70]:
torch.ones_like(x)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [71]:
torch.zeros_like(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

- using rand_like

In [88]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.1157, 0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868, 0.4920]])

# Tensor Data Types

- Find data type

In [72]:
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [7, 8, 9, 9]])

In [73]:
x.dtype

torch.int64

- assign data type

In [74]:
torch.tensor([1.0,2.0,3.0,4.0],dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [75]:
x = torch.tensor([1.0,2.0,3.9,4.5])
print(x)
x = x.to(torch.int32)
print(x)

tensor([1.0000, 2.0000, 3.9000, 4.5000])
tensor([1, 2, 3, 4], dtype=torch.int32)


- Similerly in float

In [76]:
torch.tensor([1,2,3,4],dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [77]:
x = torch.tensor([1,2,3,4])
print(x)
x = x.to(torch.float32)
print(x)

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


- using to()

In [79]:
x = torch.tensor([[1,2,3,4],[5,6,7,7]])
print(x)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 7]])


In [80]:
x=x.to(torch.float32)
print(x)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 7.]])


# Mathematical operations

- **Scaler operation**

In [91]:
x = torch.rand(2,2)
x

tensor([[0.7668, 0.1659],
        [0.4393, 0.2243]])

- addition

In [92]:
x + 3

tensor([[3.7668, 3.1659],
        [3.4393, 3.2243]])

- Substraction

In [93]:
x - 2

tensor([[-1.2332, -1.8341],
        [-1.5607, -1.7757]])

- Multiplication

In [94]:
x * 5

tensor([[3.8340, 0.8296],
        [2.1966, 1.1214]])

- division

In [95]:
x / 4

tensor([[0.1917, 0.0415],
        [0.1098, 0.0561]])

- int division

In [97]:
(x * 100) // 3

tensor([[25.,  5.],
        [14.,  7.]])

- mod

In [98]:
((x * 100) // 3)%2

tensor([[1., 1.],
        [0., 1.]])

- power

In [99]:
x**2

tensor([[0.5880, 0.0275],
        [0.1930, 0.0503]])

# Element wise operation

In [100]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.8935, 0.0497, 0.1780],
        [0.3011, 0.1893, 0.9186]])
tensor([[0.2131, 0.3957, 0.6017],
        [0.4234, 0.5224, 0.4175]])


In [102]:
# add
a + b

tensor([[1.1066, 0.4454, 0.7796],
        [0.7245, 0.7117, 1.3361]])

In [103]:
# sub
a - b

tensor([[ 0.6803, -0.3459, -0.4237],
        [-0.1223, -0.3331,  0.5011]])

In [104]:
# mul
a * b

tensor([[0.1904, 0.0197, 0.1071],
        [0.1275, 0.0989, 0.3835]])

In [105]:
# division
a / b

tensor([[4.1920, 0.1257, 0.2958],
        [0.7111, 0.3623, 2.2002]])

In [106]:
# power
a ** b

tensor([[0.9763, 0.3050, 0.3540],
        [0.6016, 0.4191, 0.9652]])

In [107]:
# mod
a % b

tensor([[0.0409, 0.0497, 0.1780],
        [0.3011, 0.1893, 0.0836]])

In [109]:
tens = torch.tensor([1,-2,3,-4])
print(tens)

tensor([ 1, -2,  3, -4])


In [110]:
# abs
torch.abs(tens)

tensor([1, 2, 3, 4])

In [111]:
# negative
torch.neg(tens)

tensor([-1,  2, -3,  4])

In [112]:
tens2 = torch.tensor([1.9,2.3,3.7,4.4])
print(tens2)

tensor([1.9000, 2.3000, 3.7000, 4.4000])


In [113]:
# round
torch.round(tens2)

tensor([2., 2., 4., 4.])

In [114]:
# ceil
torch.ceil(tens2)

tensor([2., 3., 4., 5.])

In [115]:
# floor
torch.floor(tens2)

tensor([1., 2., 3., 4.])

In [116]:
# clamp
torch.clamp(tens2,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

- Reduction operation

In [123]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[9., 0., 7.],
        [9., 2., 7.]])

- sum




In [120]:
torch.sum(e)

tensor(30)

- sum along columns

In [121]:
torch.sum(e,dim=0)

tensor([ 8, 12, 10])

- sum along rows

In [122]:
torch.sum(e,dim=1)

tensor([12, 18])

- mean

In [124]:
torch.mean(e)

tensor(5.6667)

- mean along col

In [125]:
torch.mean(e,dim=0)

tensor([9., 1., 7.])

- median

In [127]:
torch.median(e)

tensor(7.)

- max min

In [129]:
torch.min(e)

tensor(0.)

In [130]:
torch.max(e)

tensor(9.)

- product

In [132]:
torch.prod(e)

tensor(0.)

- standard deviation

In [133]:
torch.std(e)

tensor(3.7771)

- variance

In [134]:
torch.var(e)

tensor(14.2667)

- argmax

In [135]:
torch.argmax(e)

tensor(0)

- argmix

In [136]:
torch.argmin(e)

tensor(1)

# Matrix operations

In [137]:
f = torch.randint(size = (2,3), low=0,high=10)
g = torch.randint(size = (3,2), low=0,high=10)

print(f)
print(g)

tensor([[0, 2, 4],
        [4, 6, 2]])
tensor([[1, 0],
        [5, 1],
        [0, 0]])


- matrix multiplication

In [138]:
torch.matmul(f,g)

tensor([[10,  2],
        [34,  6]])

- dot product

In [139]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

- transpose

In [140]:
f

tensor([[0, 2, 4],
        [4, 6, 2]])

In [141]:
torch.transpose(f,0,1)

tensor([[0, 4],
        [2, 6],
        [4, 2]])

- determinant

In [144]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[3., 6., 7.],
        [8., 1., 2.],
        [3., 2., 7.]])

In [145]:
torch.det(h)

tensor(-200.0000)

- inverse


In [148]:
torch.inverse(h)

tensor([[-1.5000e-02,  1.4000e-01, -2.5000e-02],
        [ 2.5000e-01, -8.3446e-09, -2.5000e-01],
        [-6.5000e-02, -6.0000e-02,  2.2500e-01]])

# Comparison operations

In [149]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[9, 3, 9],
        [7, 7, 5]])
tensor([[9, 2, 2],
        [4, 8, 9]])


- greater than

In [150]:
i > j

tensor([[False,  True,  True],
        [ True, False, False]])

- less than

In [151]:
i < j

tensor([[False, False, False],
        [False,  True,  True]])

- equal to

In [152]:
i == j

tensor([[ True, False, False],
        [False, False, False]])

- not equal to

In [153]:
i != j

tensor([[False,  True,  True],
        [ True,  True,  True]])

- greater than equal to

In [154]:
i >= j

tensor([[ True,  True,  True],
        [ True, False, False]])

- less than equal to

In [155]:
i <= j

tensor([[ True, False, False],
        [False,  True,  True]])

# Special functions

In [156]:
k = torch.randint(size=(2,3),low=0,high=10)
k

tensor([[6, 1, 4],
        [5, 6, 0]])

- log

In [157]:
torch.log(k)

tensor([[1.7918, 0.0000, 1.3863],
        [1.6094, 1.7918,   -inf]])

- exp

In [158]:
torch.exp(k)

tensor([[403.4288,   2.7183,  54.5981],
        [148.4132, 403.4288,   1.0000]])

- sqrt

In [159]:
torch.sqrt(k)

tensor([[2.4495, 1.0000, 2.0000],
        [2.2361, 2.4495, 0.0000]])

- sigmoid

In [160]:
torch.sigmoid(k)

tensor([[0.9975, 0.7311, 0.9820],
        [0.9933, 0.9975, 0.5000]])

- softmax

In [161]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[4., 5., 8.],
        [0., 8., 9.]])

In [163]:
torch.softmax(k,dim=0)

tensor([[0.9820, 0.0474, 0.2689],
        [0.0180, 0.9526, 0.7311]])

In [164]:
torch.softmax(k,dim=1)

tensor([[1.7148e-02, 4.6613e-02, 9.3624e-01],
        [9.0212e-05, 2.6892e-01, 7.3099e-01]])

- relu

In [165]:
torch.relu(k)

tensor([[4., 5., 8.],
        [0., 8., 9.]])

# Inplace Operation

In [167]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3771, 0.2440, 0.8994],
        [0.1041, 0.9193, 0.6201]])
tensor([[0.3658, 0.0623, 0.5967],
        [0.0829, 0.8185, 0.4964]])


In [168]:
m + n

tensor([[0.7430, 0.3063, 1.4961],
        [0.1870, 1.7378, 1.1165]])

In [169]:
m.add_(n)

tensor([[0.7430, 0.3063, 1.4961],
        [0.1870, 1.7378, 1.1165]])

In [170]:
m

tensor([[0.7430, 0.3063, 1.4961],
        [0.1870, 1.7378, 1.1165]])

In [171]:
n

tensor([[0.3658, 0.0623, 0.5967],
        [0.0829, 0.8185, 0.4964]])

In [172]:
torch.relu(m)

tensor([[0.7430, 0.3063, 1.4961],
        [0.1870, 1.7378, 1.1165]])

In [173]:
m.relu_()

tensor([[0.7430, 0.3063, 1.4961],
        [0.1870, 1.7378, 1.1165]])

In [175]:
m

tensor([[0.7430, 0.3063, 1.4961],
        [0.1870, 1.7378, 1.1165]])

- Copying a Tensor

In [177]:
a = torch.rand(2,3)
a

tensor([[0.2557, 0.1506, 0.7856],
        [0.4152, 0.5809, 0.1088]])

In [178]:
b = a

In [179]:
b

tensor([[0.2557, 0.1506, 0.7856],
        [0.4152, 0.5809, 0.1088]])

In [180]:
a[0][0] = 0

In [181]:
a

tensor([[0.0000, 0.1506, 0.7856],
        [0.4152, 0.5809, 0.1088]])

In [182]:
b

tensor([[0.0000, 0.1506, 0.7856],
        [0.4152, 0.5809, 0.1088]])

In [183]:
id(a)

134657148962928

In [184]:
id(b)

134657148962928

In [185]:
b = a.clone()

In [186]:
a

tensor([[0.0000, 0.1506, 0.7856],
        [0.4152, 0.5809, 0.1088]])

In [187]:
b

tensor([[0.0000, 0.1506, 0.7856],
        [0.4152, 0.5809, 0.1088]])

In [188]:
a[0][0]=10

In [189]:
a

tensor([[10.0000,  0.1506,  0.7856],
        [ 0.4152,  0.5809,  0.1088]])

In [190]:
b

tensor([[0.0000, 0.1506, 0.7856],
        [0.4152, 0.5809, 0.1088]])

In [191]:
id(a)

134657148962928

In [192]:
id(b)

134657148804208